// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOLhegBe3MCA3tLyBmszQ6CJydGPK_2E',
    appId: '1:191832958284:web:79c02d7add880a426f5be9',
    messagingSenderId: '191832958284',
    projectId: 'fruits-hup-52490',
    authDomain: 'fruits-hup-52490.firebaseapp.com',
    storageBucket: 'fruits-hup-52490.firebasestorage.app',
    measurementId: 'G-8FEGN9YG43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCXI9vKPzXfhvJpRBQDF-DtjrR_qmmOY',
    appId: '1:191832958284:android:7ddb3678b0febb8f6f5be9',
    messagingSenderId: '191832958284',
    projectId: 'fruits-hup-52490',
    storageBucket: 'fruits-hup-52490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuJTk0fGa29mgGxgRS0N8S1DV5VdvXQk',
    appId: '1:191832958284:ios:89fad1013774736c6f5be9',
    messagingSenderId: '191832958284',
    projectId: 'fruits-hup-52490',
    storageBucket: 'fruits-hup-52490.firebasestorage.app',
    androidClientId: '191832958284-a7kf87n6gdnpj3bdv7csf9invg98e408.apps.googleusercontent.com',
    iosClientId: '191832958284-ijaqvuabrriu9lkdv5o4nj5dvkvirbe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuJTk0fGa29mgGxgRS0N8S1DV5VdvXQk',
    appId: '1:191832958284:ios:89fad1013774736c6f5be9',
    messagingSenderId: '191832958284',
    projectId: 'fruits-hup-52490',
    storageBucket: 'fruits-hup-52490.firebasestorage.app',
    androidClientId: '191832958284-a7kf87n6gdnpj3bdv7csf9invg98e408.apps.googleusercontent.com',
    iosClientId: '191832958284-ijaqvuabrriu9lkdv5o4nj5dvkvirbe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAOLhegBe3MCA3tLyBmszQ6CJydGPK_2E',
    appId: '1:191832958284:web:04f42960dcfe3f696f5be9',
    messagingSenderId: '191832958284',
    projectId: 'fruits-hup-52490',
    authDomain: 'fruits-hup-52490.firebaseapp.com',
    storageBucket: 'fruits-hup-52490.firebasestorage.app',
    measurementId: 'G-9KCNY9R09G',
  );

}